[[regions]]
  id="us915_0"
  description="US915 sub-band 0"
  common_name="US915"

  [regions.gateway.backend.mqtt]
    topic_prefix="us915_0"
    server="tcp://mosquitto:1883"
    username=""
    password=""
    qos=0
    clean_session=true
    client_id="chirpstack-gateway-us915"
